# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
import subprocess
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame9")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_file(pyfile):
    window.destroy()  # First close the current window
    subprocess.Popen(["python3", pyfile])

window = Tk()

window.geometry("956x661")
window.configure(bg = "#CCBF83")


canvas = Canvas(
    window,
    bg = "#CCBF83",
    height = 661,
    width = 956,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    956.0,
    87.0,
    fill="#653F7D",
    outline="")

canvas.create_text(
    116.0,
    9.0,
    anchor="nw",
    text="Flavour Fusion",
    fill="#FFFFFF",
    font=("Inika Bold", 48 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    475.0,
    147.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    246.0,
    342.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    686.0,
    335.0,
    image=image_image_3
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_file("Manage_Recipe.py"), #Manage Recipe
    relief="flat"
)
button_1.place(
    x=84.0,
    y=508.0,
    width=323.0,
    height=88.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_file("Manage_Profile.py"), #Manage Users
    relief="flat"
)
button_2.place(
    x=529.0,
    y=508.0,
    width=322.0,
    height=88.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    42.0,
    41.0,
    image=image_image_4
)

# Create rounded logout button
logout_button = Button(
    window,
    text="Logout",
    bg="#653F7D",
    fg="#653F7D",
    font=("Arial", 12, "bold"),
    bd=0,
    highlightthickness=0,
    relief="flat",
    activebackground="#653F7D",
    activeforeground="#653F7D",
    command=lambda: open_file("Homepage.py"),
    padx=20,
    pady=5
)
logout_button.place(
    x=850,
    y=25,
    width=80,
    height=40
)

# Make the button rounded
logout_button.config(
    highlightbackground="#653F7D",
    highlightcolor="#653F7D",
    borderwidth=0,
    highlightthickness=1,
    relief="solid"
)

window.resizable(False, False)
window.mainloop()