
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from Confirm import open_confirm_page

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"../assets/Payment/frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_card_page(previous_window, user_id, user_name, amount):
    previous_window.destroy()
    window = Tk()

    window.geometry("657x840")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 840,
        width = 657,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        328.0,
        420.0,
        image=image_image_1
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        328.0,
        373.5,
        image=entry_image_1
    )
    entry_1 = Text(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=97.0,
        y=341.0,
        width=462.0,
        height=63.0
    )

    canvas.create_text(
        92.0,
        317.0,
        anchor="nw",
        text="Name on Card",
        fill="#000000",
        font=("ScopeOne Regular", 15 * -1)
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        329.0,
        475.5,
        image=entry_image_2
    )
    entry_2 = Text(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=98.0,
        y=443.0,
        width=462.0,
        height=63.0
    )

    canvas.create_text(
        92.0,
        414.0,
        anchor="nw",
        text="Card Number",
        fill="#000000",
        font=("ScopeOne Regular", 15 * -1)
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        194.0,
        574.5,
        image=entry_image_3
    )
    entry_3 = Text(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_3.place(
        x=98.0,
        y=542.0,
        width=192.0,
        height=63.0
    )

    canvas.create_text(
        92.0,
        518.0,
        anchor="nw",
        text="Expiry Date",
        fill="#000000",
        font=("ScopeOne Regular", 15 * -1)
    )

    entry_image_4 = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        456.0,
        574.5,
        image=entry_image_4
    )
    entry_4 = Text(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_4.place(
        x=360.0,
        y=542.0,
        width=192.0,
        height=63.0
    )

    canvas.create_text(
        350.0,
        518.0,
        anchor="nw",
        text="Security Code",
        fill="#000000",
        font=("ScopeOne Regular", 15 * -1)
    )

    entry_image_5 = PhotoImage(
        file=relative_to_assets("entry_5.png"))
    entry_bg_5 = canvas.create_image(
        329.0,
        669.5,
        image=entry_image_5
    )
    entry_5 = Text(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_5.place(
        x=98.0,
        y=637.0,
        width=462.0,
        height=63.0
    )

    canvas.create_text(
        88.0,
        613.0,
        anchor="nw",
        text=" Enter Pincode",
        fill="#000000",
        font=("ScopeOne Regular", 15 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_confirm_page(window, user_id, user_name),
        relief="flat"
    )
    button_1.place(
        x=60.0,
        y=720.0,
        width=537.0,
        height=89.0
    )

    entry_image_6 = PhotoImage(
        file=relative_to_assets("entry_6.png"))
    entry_bg_6 = canvas.create_image(
        192.5,
        295.0,
        image=entry_image_6
    )
    entry_6 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_6.place(
        x=140.0,
        y=279.0,
        width=105.0,
        height=30.0
    )
    entry_6.insert(0, amount)
    window.resizable(False, False)
    window.mainloop()
