# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from Chat import open_Chat_page
from History import open_history_page
from Services.Driver.Driver import open_driver_page
from Services.Cooks.Cook import open_cook_page

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/Home")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_home_page(previous_window, user_id, user_name):
    previous_window.destroy()
    window = Tk()

    window.geometry("700x840")
    window.configure(bg = "#FFFFFF")

    def open_profile():
        from Profile import open_profile_page
        open_profile_page(window, user_id, user_name)

    def open_login():
        from Login import open_login_page
        open_login_page(window)

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 840,
        width = 700,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        352.0,
        422.0,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        349.0,
        200.0,
        image=image_image_2
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=39.0,
        y=251.0,
        width=174.0,
        height=126.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=40.0,
        y=462.0,
        width=174.0,
        height=126.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command= lambda: open_cook_page(window, user_id, user_name),
        relief="flat"
    )
    button_3.place(
        x=263.0,
        y=462.0,
        width=174.0,
        height=126.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_4 clicked"),
        relief="flat"
    )
    button_4.place(
        x=485.0,
        y=462.0,
        width=174.0,
        height=126.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_5 clicked"),
        relief="flat"
    )
    button_5.place(
        x=485.0,
        y=252.0,
        width=174.0,
        height=126.0
    )

    button_image_6 = PhotoImage(
        file=relative_to_assets("button_6.png"))
    button_6 = Button(
        image=button_image_6,
        borderwidth=0,
        highlightthickness=0,
        command=open_login,
        relief="flat"
    )
    button_6.place(
        x=33.0,
        y=19.0,
        width=77.0,
        height=31.0
    )

    button_image_7 = PhotoImage(
        file=relative_to_assets("button_7.png"))
    button_7 = Button(
        image=button_image_7,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_driver_page(window, user_id, user_name),
        relief="flat"
    )
    button_7.place(
        x=259.0,
        y=252.0,
        width=174.0,
        height=126.0
    )

    canvas.create_text(
        487.0,
        121.0,
        anchor="nw",
        text=f"Hello {user_name}!",
        fill="#000000",
        font=("RoundedMplus1c Bold", 24 * -1)
    )

    button_image_8 = PhotoImage(
        file=relative_to_assets("button_8.png"))
    button_8 = Button(
        image=button_image_8,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_8 clicked"),
        relief="flat"
    )
    button_8.place(
        x=618.0,
        y=19.0,
        width=34.0,
        height=34.0
    )

    button_image_9 = PhotoImage(
        file=relative_to_assets("button_9.png"))
    button_9 = Button(
        image=button_image_9,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_9 clicked"),
        relief="flat"
    )
    button_9.place(
        x=59.0,
        y=746.0,
        width=49.0,
        height=49.0
    )

    button_image_10 = PhotoImage(
        file=relative_to_assets("button_10.png"))
    button_10 = Button(
        image=button_image_10,
        borderwidth=0,
        highlightthickness=0,
        command=open_profile,
        relief="flat"
    )
    button_10.place(
        x=612.0,
        y=746.0,
        width=49.0,
        height=49.0
    )

    button_image_11 = PhotoImage(
        file=relative_to_assets("button_11.png"))
    button_11 = Button(
        image=button_image_11,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_history_page(window, user_id, user_name),
        relief="flat"
    )
    button_11.place(
        x=423.0,
        y=746.0,
        width=49.0,
        height=49.0
    )

    button_image_12 = PhotoImage(
        file=relative_to_assets("button_12.png"))
    button_12 = Button(
        image=button_image_12,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_Chat_page(window, user_id, user_name),
    )
    button_12.place(
        x=245.0,
        y=746.0,
        width=49.0,
        height=49.0
    )
    window.resizable(False, False)
    window.mainloop()








