
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Aayush\OneDrive\Documents\Findr-GUI\PetCare\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x840")
window.configure(bg = "#ECECEE")


canvas = Canvas(
    window,
    bg = "#ECECEE",
    height = 840,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    245.0,
    700.0,
    335.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    700.0,
    84.0,
    fill="#044389",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=29.0,
    y=27.0,
    width=77.0,
    height=31.0
)

canvas.create_text(
    41.0,
    192.0,
    anchor="nw",
    text="\n\nAvailable: 9 AM to 10 PM\n\n",
    fill="#000000",
    font=("Montserrat Regular", 32 * -1)
)

canvas.create_rectangle(
    0.0,
    341.0,
    700.0,
    431.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    29.0,
    372.0,
    anchor="nw",
    text=" Specializes Maintaining clean cages",
    fill="#000000",
    font=("Montserrat Regular", 32 * -1)
)

canvas.create_rectangle(
    0.0,
    438.0,
    700.0,
    528.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    29.0,
    449.0,
    anchor="nw",
    text=" ₹1100 per visit | ₹2000 for emergency service",
    fill="#000000",
    font=("Montserrat Regular", 32 * -1)
)

canvas.create_rectangle(
    0.0,
    535.0,
    700.0,
    625.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    29.0,
    561.0,
    anchor="nw",
    text="Years of Experience :- 11 Years",
    fill="#000000",
    font=("Montserrat Regular", 32 * -1)
)

canvas.create_rectangle(
    0.0,
    632.0,
    700.0,
    722.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    45.0,
    661.0,
    anchor="nw",
    text="Average Rating :- (⭐ 3/5)",
    fill="#000000",
    font=("Montserrat Regular", 32 * -1)
)

canvas.create_text(
    184.0,
    132.0,
    anchor="nw",
    text="Name :- Sharmila Pinto",
    fill="#000000",
    font=("Montserrat Regular", 32 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    89.0,
    164.0,
    image=image_image_1
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=163.0,
    y=751.0,
    width=338.1076354980469,
    height=66.0
)
window.resizable(False, False)
window.mainloop()
