
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from Services.Driver.Driver1 import open_driver1_page
from Services.Driver.Driver2 import open_driver2_page
from Services.Driver.Driver3 import open_driver3_page
from Services.Driver.Driver4 import open_driver4_page

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"../../assets/Services/Driver/frame0") #copy the path only replace Driver with folder name


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_driver_page(previous_window, user_id, user_name):  # put these two line and select code and press tab
    previous_window.destroy()
    window = Tk()

    window.geometry("700x840")
    window.configure(bg = "#FFFFFF")

    def open_home():
        from Home import open_home_page
        open_home_page(window, user_id, user_name)

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 840,
        width = 700,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        100.0,
        130.0,
        349.0,
        188.0,
        fill="#D9D9D9",
        outline="")

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=1.0,
        y=0.0,
        width=701.0,
        height=84.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=open_home, #Home
        relief="flat"
    )
    button_2.place(
        x=27.0,
        y=27.0,
        width=77.0,
        height=31.0
    )

    canvas.create_text(
        111.0,
        130.0,
        anchor="nw",
        text="Driver",
        fill="#000000",
        font=("RoundedMplus1c Bold", 36 * -1)
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_driver1_page(window, user_id, user_name), #Driver1
        relief="flat"
    )
    button_3.place(
        x=0.0,
        y=259.0,
        width=700.0,
        height=116.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_driver2_page(window, user_id, user_name), #Driver2
        relief="flat"
    )
    button_4.place(
        x=0.0,
        y=404.0,
        width=700.0,
        height=116.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_driver3_page(window, user_id, user_name), #Driver3
        relief="flat"
    )
    button_5.place(
        x=1.0,
        y=550.0,
        width=700.0,
        height=116.0
    )

    button_image_6 = PhotoImage(
        file=relative_to_assets("button_6.png"))
    button_6 = Button(
        image=button_image_6,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_driver4_page(window, user_id, user_name), #Driver4
        relief="flat"
    )
    button_6.place(
        x=1.0,
        y=696.0,
        width=700.0,
        height=116.0
    )

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        61.0,
        153.0,
        image=image_image_1
    )
    window.resizable(False, False)
    window.mainloop()
