
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"../../assets/Services/Driver/frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_driver1_page(previous_window, user_id, user_name):
    previous_window.destroy()
    window = Tk()
    sname= "Aakash Kumar"
    service= "Driver"
    amount = 600
    window.geometry("700x840")
    window.configure(bg = "#E0E0E0")

    def open_driver():
        from Services.Driver.Driver import open_driver_page
        open_driver_page(window, user_id, user_name)

    def out_driver1():
        from Details import open_details_page
        open_details_page(window, sname, amount, service, user_id, user_name)

    canvas = Canvas(
        window,
        bg = "#E0E0E0",
        height = 840,
        width = 700,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=out_driver1, #details
        relief="flat"
    )
    button_1.place(
        x=198.0,
        y=753.0,
        width=338.0,
        height=66.0
    )

    canvas.create_rectangle(
        0.0,
        245.0,
        700.0,
        335.0,
        fill="#D9D9D9",
        outline="")

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=0.0,
        y=0.0,
        width=700.0,
        height=84.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=open_driver, #driver
        relief="flat"
    )
    button_3.place(
        x=29.0,
        y=27.0,
        width=77.0,
        height=31.0
    )

    canvas.create_text(
        41.0,
        192.0,
        anchor="nw",
        text="\n\nAvailable: 9 AM to 10 PM\n\n",
        fill="#000000",
        font=("Montserrat Regular", 32 * -1)
    )

    canvas.create_rectangle(
        0.0,
        341.0,
        700.0,
        431.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        29.0,
        368.0,
        anchor="nw",
        text=" Friendly and Automotive Car driver",
        fill="#000000",
        font=("Montserrat Regular", 32 * -1)
    )

    canvas.create_rectangle(
        0.0,
        438.0,
        700.0,
        528.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        29.0,
        449.0,
        anchor="nw",
        text=" ₹600 per visit | ₹2700 for emergency service",
        fill="#000000",
        font=("Montserrat Regular", 32 * -1)
    )

    canvas.create_rectangle(
        0.0,
        535.0,
        700.0,
        625.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        29.0,
        561.0,
        anchor="nw",
        text="Years of Experience :- 10 Years",
        fill="#000000",
        font=("Montserrat Regular", 32 * -1)
    )

    canvas.create_rectangle(
        0.0,
        632.0,
        700.0,
        722.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        45.0,
        661.0,
        anchor="nw",
        text="Average Rating :- (⭐ 3.5/5)",
        fill="#000000",
        font=("Montserrat Regular", 32 * -1)
    )

    canvas.create_text(
        184.0,
        132.0,
        anchor="nw",
        text="Name :- Aakash Kumar",
        fill="#000000",
        font=("Montserrat Regular", 32 * -1)
    )

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        95.0,
        166.0,
        image=image_image_1
    )
    window.resizable(False, False)
    window.mainloop()
