from .welcome_page import WelcomePage
from .login_page import LoginPage
from .dashboard_page import DashboardPage
from .create_account_page import CreateAccountPage
from .mock_tests_page import MockTestsPage
from .forgot_password_page import ForgotPasswordPage
from .previous_year_questions_page import PreviousYearQuestionsPage
from .reports_page import ReportsPage
from .news_page import NewsPage