
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from Review import open_review_page

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/Confirm")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_confirm_page(previous_window, user_id, user_name):
    previous_window.destroy()
    window = Tk()

    window.geometry("700x840")
    window.configure(bg = "#E0E0E0")

    def open_home():
        from Home import open_home_page
        open_home_page(window, user_id, user_name)

    canvas = Canvas(
        window,
        bg = "#E0E0E0",
        height = 840,
        width = 700,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        350.0,
        420.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=open_home,
        relief="flat"
    )
    button_1.place(
        x=26.0,
        y=710.0,
        width=648.0,
        height=95.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_review_page(window, user_id, user_name),
        relief="flat"
    )
    button_2.place(
        x=407.0,
        y=623.0,
        width=255.37767028808594,
        height=52.344825744628906
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_3.place(
        x=24.0,
        y=22.0,
        width=87.0,
        height=41.0
    )
    window.resizable(False, False)
    window.mainloop()
