
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from database import create_connection


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/Details")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_details_page(previous_window, sname, amount, service, user_id, user_name):
    previous_window.destroy()
    window = Tk()

    window.geometry("700x840")
    window.configure(bg = "#ECECEE")

    def open_payment():
        # Get input values
        dd = entry_6.get()
        mm = entry_4.get()
        yyyy = entry_5.get()
        hh = entry_7.get()
        mi = entry_8.get()
        
        # Create new database connection
        conn = create_connection()
        if conn is not None:
            try:
                cursor = conn.cursor()
                # Update query with correct column names
                update_query = """
                    INSERT into history (uid, sname, service, amount, 
                        dd, mm, yyyy, hh, min) 
                    values (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                """
                update_values = (user_id, sname, service, amount, dd, mm, yyyy, hh, mi)
                
                cursor.execute(update_query, update_values)
                conn.commit()
                
                from Payment.Payment import open_payment_page
                open_payment_page(window, user_id, user_name, amount)
                
            except Exception as e:
                print(f"Database error: {e}")
                conn.rollback()
            finally:
                cursor.close()
                conn.close()
        else:
            print("Failed to connect to database")

    canvas = Canvas(
        window,
        bg = "#ECECEE",
        height = 840,
        width = 700,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    conn = create_connection()
    if conn is not None:
        cursor = conn.cursor()
        cursor.execute("SELECT address FROM users WHERE id = %s", (user_id,))
        user_data = cursor.fetchone()
        cursor.close()
        conn.close()

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        350.0,
        420.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=open_payment, #Payment
        relief="flat"
    )
    button_1.place(
        x=26.0,
        y=719.0,
        width=648.0,
        height=95.0
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        210.0,
        232.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=34.0,
        y=211.0,
        width=352.0,
        height=40.0
    )
    entry_1.insert(0, sname) #Name

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        335.0,
        614.5,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=35.0,
        y=584.0,
        width=600.0,
        height=59.0
    )
    entry_2.insert(0, user_data[0]) #address

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        142.5,
        514.0,
        image=entry_image_3
    )
    entry_3 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_3.place(
        x=34.0,
        y=493.0,
        width=217.0,
        height=40.0
    )
    entry_3.insert(0, service) #type of service

    entry_image_4 = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        169.5,
        335.0,
        image=entry_image_4
    )
    entry_4 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_4.place(
        x=141.0,
        y=314.0,
        width=57.0,
        height=40.0
    )
    entry_4.insert(0, "mm") #mm

    entry_image_5 = PhotoImage(
        file=relative_to_assets("entry_5.png"))
    entry_bg_5 = canvas.create_image(
        275.5,
        335.0,
        image=entry_image_5
    )
    entry_5 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_5.place(
        x=247.0,
        y=314.0,
        width=57.0,
        height=40.0
    )
    entry_5.insert(0, "yyyy") #yyyy

    entry_image_6 = PhotoImage(
        file=relative_to_assets("entry_6.png"))
    entry_bg_6 = canvas.create_image(
        63.5,
        335.0,
        image=entry_image_6
    )
    entry_6 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_6.place(
        x=35.0,
        y=314.0,
        width=57.0,
        height=40.0
    )
    entry_6.insert(0, "dd") #dd

    entry_image_7 = PhotoImage(
        file=relative_to_assets("entry_7.png"))
    entry_bg_7 = canvas.create_image(
        63.5,
        428.0,
        image=entry_image_7
    )
    entry_7 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_7.place(
        x=35.0,
        y=407.0,
        width=57.0,
        height=40.0
    )
    entry_7.insert(0, "hh") #hh

    entry_image_8 = PhotoImage(
        file=relative_to_assets("entry_8.png"))
    entry_bg_8 = canvas.create_image(
        159.5,
        428.0,
        image=entry_image_8
    )
    entry_8 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_8.place(
        x=131.0,
        y=407.0,
        width=57.0,
        height=40.0
    )
    entry_8.insert(0, "mm") #mm

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"), #back
        relief="flat"
    )
    button_2.place(
        x=24.0,
        y=22.0,
        width=87.0,
        height=41.0
    )

    canvas.create_text(
        220.0,  # x position
        694.0,  # y position (above the button which starts at y=719)
        text=f"₹{amount}",  # Display the amount variable
        fill="#000000",
        font=("Inter", 22 * -1),
        anchor="center"
    )
    window.resizable(False, False)
    window.mainloop()
