
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox

from database import create_connection


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/Login")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def open_login_page(previous_window):
    previous_window.destroy()
    
    window = Tk()

    window.geometry("700x840")
    window.configure(bg = "#E0E0CE")

    def login():
        email = entry_2.get()
        password = entry_1.get()
        
        conn = create_connection()
        if conn is not None:
            cursor = conn.cursor()
            cursor.execute("SELECT id, name FROM users WHERE email = %s AND password = %s", (email, password))
            user = cursor.fetchone()
            cursor.close()
            conn.close()
            
            if user:
                from Home import open_home_page
                open_home_page(window, user[0], user[1])
            else:
                messagebox.showerror("Error", "Invalid email or password")

    def open_signup():
        from SignUp import open_signup_page
        open_signup_page(window)

    def open_reset():
        emailuser = entry_2.get()
        if not emailuser:
            messagebox.showerror("Error", "Enter Email")
            return
        from Reset import open_reset_page
        open_reset_page(window, emailuser)

    canvas = Canvas(
        window,
        bg = "#E0E0CE",
        height = 840,
        width = 700,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        352.0,
        422.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=login,
        relief="flat"
    )
    button_1.place(
        x=53.0,
        y=675.0,
        width=187.0,
        height=47.0
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        172.0,
        571.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=24.0,
        y=550.0,
        width=296.0,
        height=40.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        172.5,
        459.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=25.0,
        y=438.0,
        width=295.0,
        height=40.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command= lambda: open_reset(), #forget Pass
        relief="flat"
    )
    button_2.place(
        x=25.0,
        y=601.0,
        width=124.0,
        height=15.0
    )
    

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command= open_signup,
        relief="flat"
    )
    button_3.place(
        x=601.0,
        y=742.0,
        width=53.0,
        height=16.0
    )

    canvas.create_rectangle(
        50.0,
        637.0,
        187.0,
        655.0,
        fill="#E0E0CE",
        outline="")
    window.resizable(False, False)
    window.mainloop()
