
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox

from database import create_connection


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/Reset")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_reset_page(previous_window, user_email):
    previous_window.destroy()
    window = Tk()

    window.geometry("700x840")
    window.configure(bg = "#FFFFFF")

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 840,
        width = 700,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        350.0,
        420.0,
        image=image_image_1
    )

    canvas.create_text(
        56.0,
        806.0,
        anchor="nw",
        text="@Findr",
        fill="#044389",
        font=("RoundedMplus1c Bold", 20 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        157.5,
        376.5,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=21.0,
        y=358.0,
        width=273.0,
        height=35.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        157.5,
        505.5,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=21.0,
        y=487.0,
        width=273.0,
        height=35.0
    )

    def reset_pass():
        password = entry_1.get()
        
        if not password:
            messagebox.showerror("Error", "Password required")
            return
        
        if entry_1.get() != entry_2.get():
            messagebox.showerror("Error", "Password does not match!")
            return
        conn = create_connection()
        if conn is not None:
            try:
                cursor = conn.cursor()
                update_values = (password, user_email)
                
                cursor.execute(
                    "UPDATE users SET password=%s WHERE email=%s",
                    update_values)
                
                conn.commit()
                messagebox.showinfo("Success", "Password reset successful!")
                from Login import open_login_page
                open_login_page(window)
            except Exception as e:
                messagebox.showerror("Error", f"Failed to reset password: {str(e)}")
            finally:
                cursor.close()
                conn.close()

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=reset_pass,
        relief="flat"
    )
    button_1.place(
        x=112.6875,
        y=689.0,
        width=218.3125,
        height=47.0
    )
    window.resizable(False, False)
    window.mainloop()
