
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox

import mysql
from database import create_connection


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/SignUp")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_signup_page(previous_window):
    previous_window.destroy()
    window = Tk()

    window.geometry("700x840")
    window.configure(bg = "#FFFFFF")

    def signup():
            name = entry_2.get()
            email = entry_3.get()
            password = entry_1.get()
            
            if not name or not email or not password:
                messagebox.showerror("Error", "Name, Email and Password are required")
                return
                
            conn = create_connection()
            if conn is not None:
                try:
                    cursor = conn.cursor()
                    cursor.execute(
                        "INSERT INTO users (name, email, password) VALUES (%s, %s, %s)",
                        (name, email, password)
                    )
                    conn.commit()
                    cursor.close()
                    conn.close()
                    messagebox.showinfo("Success", "Account created successfully!")
                    open_login()
                except mysql.connector.Error as err:
                    messagebox.showerror("Error", f"Failed to create account: {err}")

    def open_login():
        from Login import open_login_page
        open_login_page(window)

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 840,
        width = 700,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        350.0,
        420.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=signup,
        relief="flat"
    )
    button_1.place(
        x=56.0,
        y=682.0,
        width=187.0,
        height=47.0
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        178.5,
        589.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=31.0,
        y=568.0,
        width=295.0,
        height=40.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        177.5,
        409.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=30.0,
        y=388.0,
        width=295.0,
        height=40.0
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        178.5,
        495.0,
        image=entry_image_3
    )
    entry_3 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_3.place(
        x=31.0,
        y=474.0,
        width=295.0,
        height=40.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command= open_login,
        relief="flat"
    )
    button_2.place(
        x=575.0,
        y=737.0,
        width=46.0,
        height=25.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_3.place(
        x=32.0,
        y=640.0,
        width=15.0,
        height=15.0
    )
    window.resizable(False, False)
    window.mainloop()
