
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"../../assets/Services/Cleaner/frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_Cleaner1_page(previous_window, user_id, user_name):  # put these two line and select code and press tab
    previous_window.destroy()
    window = Tk()
    sname= "Jessica & John" #Cleaner name
    service= "Cleaner"         #type
    amount = 300            #amount
    window.geometry("700x840")
    window.configure(bg = "#ECECEE")

    def open_cook(): #opens Cleaner page. refer the import path
        from Services.Cleaner.Cleaner import open_Cleaner_page
        open_Cleaner_page(window, user_id, user_name)

    def out_driver1():
        from Details import open_details_page
        open_details_page(window, sname, amount, service, user_id, user_name)

    canvas = Canvas(
        window,
        bg = "#ECECEE",
        height = 840,
        width = 700,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        245.0,
        700.0,
        335.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_rectangle(
        0.0,
        0.0,
        700.0,
        84.0,
        fill="#044389",
        outline="")

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=out_Cleaner1, #details
        relief="flat"
    )
    button_1.place(
        x=29.0,
        y=27.0,
        width=77.0,
        height=31.0
    )

    canvas.create_text(
        41.0,
        192.0,
        anchor="nw",
        text="\n\nAvailable: 9 AM to 10 PM\n\n",
        fill="#000000",
        font=("Montserrat Regular", 32 * -1)
    )

    canvas.create_rectangle(
        0.0,
        341.0,
        700.0,
        431.0,
        fill="#D9D9D9",
        outline="")

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        353.0,
        391.0,
        image=image_image_1
    )

    canvas.create_rectangle(
        0.0,
        438.0,
        700.0,
        528.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        41.0,
        449.0,
        anchor="nw",
        text=" ₹300 per visit | ₹1700 for emergency service",
        fill="#000000",
        font=("Montserrat Regular", 32 * -1)
    )

    canvas.create_rectangle(
        0.0,
        535.0,
        700.0,
        625.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        53.0,
        562.0,
        anchor="nw",
        text="Years of Experience :- 8 Years",
        fill="#000000",
        font=("Montserrat Regular", 32 * -1)
    )

    canvas.create_rectangle(
        0.0,
        632.0,
        700.0,
        722.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        60.0,
        663.0,
        anchor="nw",
        text="Average Rating :- (⭐ 4.2/5)",
        fill="#000000",
        font=("Montserrat Regular", 32 * -1)
    )

    canvas.create_text(
        195.0,
        132.0,
        anchor="nw",
        text="Name :- Jessica & John",
        fill="#000000",
        font=("Montserrat Regular", 32 * -1)
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        107.0,
        151.0,
        image=image_image_2
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=out_cleaner1, #opens cleaner page
        relief="flat"
    )
    button_2.place(
        x=181.0,
        y=758.0,
        width=338.1076354980469,
        height=66.0
    )
    window.resizable(False, False)
    window.mainloop()
