
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from Confirm import open_confirm_page


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"../assets/Payment/frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_gpay_page(previous_window, user_id, user_name, amount):
    previous_window.destroy()
    window = Tk()

    window.geometry("657x840")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 840,
        width = 657,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        328.0,
        420.0,
        image=image_image_1
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        329.0,
        362.5,
        image=entry_image_1
    )
    entry_1 = Text(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=98.0,
        y=330.0,
        width=462.0,
        height=63.0
    )

    canvas.create_text(
        107.0,
        292.0,
        anchor="nw",
        text="UPI ID: ",
        fill="#000000",
        font=("ScopeOne Regular", 15 * -1)
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        159.5,
        262.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=107.0,
        y=246.0,
        width=105.0,
        height=30.0
    )
    entry_2.insert(0, amount)

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_confirm_page(window, user_id, user_name),
        relief="flat"
    )
    button_1.place(
        x=60.0,
        y=717.0,
        width=537.0,
        height=89.0
    )
    window.resizable(False, False)
    window.mainloop()
