
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from Payment.paypal import open_paypal_page
from Payment.gpay import open_gpay_page
from Payment.card import open_card_page

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"../assets/Payment/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_payment_page(previous_window, user_id, user_name, amount):
    previous_window.destroy()
    window = Tk()

    window.geometry("657x840")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 840,
        width = 657,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        328.0,
        420.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"), #next step
        relief="flat"
    )
    button_1.place(
        x=60.0,
        y=655.0,
        width=537.0,
        height=129.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_paypal_page(window, user_id, user_name, amount), #paypal
        relief="flat"
    )
    button_2.place(
        x=60.0,
        y=358.0,
        width=537.0,
        height=99.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_card_page(window, user_id, user_name, amount), #card
        relief="flat"
    )
    button_3.place(
        x=60.0,
        y=259.0,
        width=537.0,
        height=99.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_gpay_page(window, user_id, user_name, amount), #gpay
        relief="flat"
    )
    button_4.place(
        x=60.0,
        y=556.0,
        width=537.0,
        height=99.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_5 clicked"), #pay after service
        relief="flat"
    )
    button_5.place(
        x=60.0,
        y=457.0,
        width=537.0,
        height=99.0
    )
    window.resizable(False, False)
    window.mainloop()
